---
title: "Piedmont Triad Simulation Parameters"
author: "Sarah Lotspeich"
date: "2024-02-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

# Load Data

```{r, echo = FALSE, warning = FALSE, message = FALSE}
# Load packages 
library(ggplot2) ## for maps and other plots
library(tidycensus) ## for shapefiles
library(possum) ## for imputation 
library(spdep) ## for adjacency matrix
library(spaMM) ## for spatial mixed-effects model

# Load data 
food_access = read.csv(file = "https://raw.githubusercontent.com/sarahlotspeich/food_access_imputation/main/piedmont-triad-data/analysis_data.csv")

## Inspect merged dataset (used for analysis)
food_access |> 
  summary()
```

  -   Median population: $4095$ people per census tract

```{r}
summary(food_access$Y_DIABETES/food_access$O_POP) ## Summarize prevalence of diabetes 
```

  -   Median prevalence of diabetes: $0.11$
  
```{r}
summary(food_access$Y_OBESITY/food_access$O_POP) ## Summarize prevalence of obesity 
```

  -   Median prevalence of obesity: $0.34$

# Additive and Multiplicative Errors

```{r}
food_access |> 
  ggplot(aes(x = X_full, y = Xstar)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  geom_abline(intercept = 0, slope = 1, linetype = 2) + 
  theme_minimal()
```

```{r}
## Add "error" between straight-line and map-based distances
food_access = food_access |> 
  dplyr::mutate(U = Xstar - X_full, 
                W = Xstar / X_full,
                LocationID = as.character(LocationID))

## Summarize distribution of errors
food_access |>
  dplyr::select(U, W) |>
  summary()

## Standard deviation of errors
food_access |> 
  dplyr::summarize(sdU = sd(U), 
                   sdW = sd(W))
```



```{r}
fitU = lm(formula = U ~ 1, data = food_access)
(params_list = list(mean = fitU$coefficients, 
                    sd = sigma(fitU)))
```

```{r, fig.cap = "Histogram of additive errors", warning = FALSE, message = FALSE, echo = FALSE}
food_access |> 
  ggplot(aes(x = U)) + 
  geom_histogram(aes(y = ..density..)) + 
  geom_density() + 
  stat_function(fun = dnorm, color = "blue", 
                args = params_list) + 
  xlab(latex2exp::TeX("$U = X^* - X$")) + 
  theme_minimal() 
```

```{r}
fitW = lm(formula = W ~ 1, data = food_access)
(params_list = list(mean = fitW$coefficients, 
                    sd = sigma(fitW)))
```
```{r, fig.cap = "Histogram of multiplicative errors", warning = FALSE, message = FALSE, echo = FALSE}
food_access |> 
  ggplot(aes(x = W)) + 
  geom_histogram(aes(y = ..density..)) + 
  geom_density() + 
  stat_function(fun = dnorm, 
                color = "blue", 
                args = params_list) +   
  xlab(latex2exp::TeX("$W = X^*/X$")) + 
  theme_minimal() 
```

```{r map of additive errors, fig.cap = "Choropleth map of the differences between straight-line and map-based proximity to healthy foods store for neighborhoods in the Piedmont Triad, North Carolina", echo = F, cache = TRUE, eval = FALSE}
ggplot() + 
  geom_sf(data = food_access, 
          aes(fill = U, geometry = geometry)) + 
  geom_sf(data = counties, 
          aes(geometry = geometry), 
          color = "black", fill = NA, size = 25) +  
  scale_fill_viridis_c(option = "viridis", 
                       name = "", #"Additive Error in Straight-Line Proximity to Healthy Foods (in Miles):", 
                       guide = guide_colourbar(direction = "vertical",
                                               barwidth = 1, barheight = 10)) +
  theme_void() + 
  theme(legend.position = "right")
```

# Models 

## Gold Standard Non-Spatial Analysis

```{r gold standard model fits, warning = FALSE}
# Model 1b: Diagnosed diabetes among adults aged >=18 years 
## Predictor X = proximity to healthy foods based on map-based distance
mod_diab = glm(formula = Y_DIABETES ~ X_full, 
               family = poisson(link = "log"), 
               offset = log(O_POP),
               data = food_access)
summary(mod_diab)

# Model 2b: Obesity among adults aged >=18 years
## Predictor X = proximity to healthy foods based on map-based distance
mod_obes = glm(formula = Y_OBESITY ~ X_full,
               family = poisson(link = "log"), 
               offset = log(O_POP),
               data = food_access)
summary(mod_obes)
```

## Gold Standard Spatial Analysis 

```{r}
## Source a script to build adjacency matrix for census tracts in the Piedmont Triad as 
### --> adj_matrix
devtools::source_url("https://raw.githubusercontent.com/sarahlotspeich/food_access_imputation/refs/heads/main/piedmont-triad-data/piedmont_adjacency_matrix.R?raw=TRUE")

# Model 1a: Diagnosed diabetes among adults aged >=18 years 
## Predictor X = proximity to healthy foods based on map-based distance
mod_diab = fitme(formula = Y_DIABETES ~ X_full + adjacency(1 | LocationID) + offset(log(O_POP)), 
                 family = poisson(link = "log"), 
                 adjMatrix = adj_matrix,
                 data = food_access)
summary(mod_diab)

# Model 2a: Obesity among adults aged >=18 years
## Predictor X = proximity to healthy foods based on map-based distance
mod_obes = fitme(formula = Y_OBESITY ~ X_full + adjacency(1 | LocationID) + offset(log(O_POP)), 
                 family = poisson(link = "log"), 
                 adjMatrix = adj_matrix,
                 data = food_access)
summary(mod_obes)
```